273 root node
phylovi/libsbn pull request #346
Opened 2021-07-15 23:33 UTC by shokiami

## Description

Added root_node_, a SubsplitDAGNode with id SIZE_MAX.
Removed the rootsplits_ indexer.
Refactored `IsRootsplit()` in SubsplitDAGNode.

Closes #273 

## Tests

A test case `"GPInstance: test root node and rootsplits"` in gp_doctest.cpp that checks if `IsRootsplit()` is implemented correctly, each rootsplit has only one parent (the root node), and if the root node id is correct.

## Checklist:

<<<<<<< HEAD
* [ ] The code uses informative and accurate variable and function names
* [ ] The functionality is factored out into functions and methods with logical interfaces
* [ ] Comments are up to date, document intent, and there are no commented-out code blocks
* [ ] Commenting and/or documentation is sufficient for others to be able to understand intent and implementation
* [ ] Entities are named according to our conventions
* [ ] Tests are present for new functionality, and these tests fail when perturbed
* [ ] `const` used where appropriate
* [ ] The code uses modern C++ conventions, including range-for, `auto`, and structured bindings
* [ ] `make format` has been run
* [ ] TODOs have been eliminated from the code
* [ ] The corresponding issue number (e.g. `#278`) has been searched for in the code to find relevant notes
=======
* [ ] Code follows our detailed [contribution guidelines](CONTRIBUTING.md)
* [ ] `clang-format` has been run
* [ ] TODOs have been eliminated from the code
* [ ] Comments are up to date, document intent, and there are no commented-out code blocks
>>>>>>> Add CONTRIBUTING document

2021-07-16 11:24 UTC, matsen requested changes
Wow! Nice work!

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.cpp
> +  IterateOverRootsplitIds([this, &gpcsp_indexer](size_t rootsplit_id) {
Are you sure that we can't get rid of this sort of special purpose code by generalizing the traversals? I would have thought that we could add the rootsplit-associated edges to the traversal and get rid of this.

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.cpp
> +size_t SubsplitDAG::RootsplitIndexOfId(size_t rootsplit_id) const {
I'm going to need to be convinced that this method needs to exist at all given the excellent addition of the DAG root!

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.cpp
> +void SubsplitDAG::CreateRootNode() {
CreateDAGRootNode here, please

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.cpp
> +  root_node_ = std::make_unique<SubsplitDAGNode>(root_node_id_, rootset);
```suggestion
  dag_root_node_ = std::make_unique<SubsplitDAGNode>(root_node_id_, rootset);
```

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.cpp
> +  // We will create a root node with a bitset where the first half is all zeros and the
This is great documentation but I think it deserves slightly higher prominence, say in the header file.

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.hpp
> +  // Root node is not counted towards total node count.
🤔 this is non-obvious. If we want to maintain this behavior, should we call it something else, like `SubsplitCount`? Have a think.

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.cpp
>  void SubsplitDAG::CreateAndInsertNode(const Bitset &subsplit) {
It's a little crazy because how big SIZE_MAX is, but I'd like to assert here that this new proposed id is less than the dag root id. 😁

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.hpp
> +  // Create a gpcsp indexer from ReversePostorderIndexTraversal.
```suggestion
  // Create a GPCSPIndexer representing the DAG.
```

(Comments for public methods should describe intent, not implementation.)

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag.hpp
> +  static constexpr size_t root_node_id_ = SIZE_MAX;
```suggestion
  static constexpr size_t dag_root_node_id_ = SIZE_MAX;
```

2021-07-16 11:24 UTC, matsen commented on src/subsplit_dag_node.hpp
> +  bool IsRootNode() const {
```suggestion
  bool IsDAGRootNode() const {
```

2021-07-19 21:17 UTC, matsen requested changes

2021-07-19 21:17 UTC, matsen commented on src/subsplit_dag.cpp
> +// Can we permanentely remove this? #273
Did you check the rest of the code?

2021-07-19 21:17 UTC, matsen commented on src/subsplit_dag.cpp
> +  // topology_count_below_ is includes an index for the DAG root (phantom_root_id).
```suggestion
  // topology_count_below_ includes an index for the DAG root (phantom_root_id).
```

2021-07-26 13:05 UTC, matsen requested changes
AMAZING! 

I've added some suggestions--- have a look and we'll chat!

2021-07-26 13:05 UTC, matsen commented on src/subsplit_dag.hpp
> +  size_t dag_root_node_id_;
Let's add a comment about this one.

2021-07-26 20:46 UTC, shokiami commented on src/subsplit_dag_node.hpp
> +    return subsplit_.Count() == subsplit_.SubsplitChunkSize() && !IsDAGRootNode();
@matsen I see what you are saying about the IsRootsplit() method, but I am confused as to how this also applies to IsDAGRootNode() as it doesn't use bitsets.

2021-07-26 20:56 UTC, matsen commented on src/subsplit_dag_node.hpp
> +    return subsplit_.Count() == subsplit_.SubsplitChunkSize() && !IsDAGRootNode();
Indeed! Perhaps I was looking at `IsRootsplit`, which does?

2021-07-26 23:19 UTC, matsen commented on data/DS1.subsampled_10.t_support.json
> +{"rootsplit_supp_dict": {"111110011111111111111111111000001100000000000000000000": 1.0, "111111110111111111111111111000000001000000000000000000": 5.0, "11111111100001111111111111100000000011110000000
That's great! Just curious.

2021-07-30 12:31 UTC, matsen requested changes
Just a few things to address here. NICE WORK!

* Do we want to reduce some of the ambiguity between rootsplit and DAG root by replacing the latter with "UA" for universal ancestor or something?
* I think the code links to a bunch of images that are now out of date, for example in https://github.com/phylovi/libsbn/issues/307#issuecomment-766148007 (which appears in tidy_subsplit_dag.hpp), and https://github.com/phylovi/libsbn/issues/323#issuecomment-787963552 (which appears in gp_doctest). There is also `doc/svg/subsplit-dag-unconditional-probabilities.svg` and one other SVG. Can you take a look at these and see what needs regenerating with the new conventions?

2021-07-30 12:31 UTC, matsen commented on src/subsplit_dag.cpp
> +  // Finally, we add the DAG root node. The DAG root node's subsplit bitset
This is a great comment, but could we put it somewhere a little more visible? Also, I think that I suggested above that we just factor this bitset creation into a Bitset function?

2021-07-30 12:31 UTC, matsen commented on src/subsplit_dag.cpp
> +  if (include_dag_root_node) {
This is a great solution!

2021-07-30 12:31 UTC, matsen commented on src/subsplit_dag.hpp
> +  // Has option to include or exclude the DAG root node from traversal.
```suggestion
  // Has option to include the DAG root node in the traversal.
```

2021-07-30 12:31 UTC, matsen commented on src/tidy_subsplit_dag.hpp
> +  // Has option to include or exclude the DAG root node from traversal.
```suggestion
  // Has option to include the DAG root node in the traversal.
```

2021-07-31 11:33 UTC, matsen approved these changes

2021-07-31 12:48 UTC, merged